.github/workflows/issue-assigner.yml
> 변경 사항 설명
- issue assigner 자동 할당 기능 구현
- x
- x
- x
- x
- close #26
=> [Feature/26] issue assignees 할당 자동화

.github/CODEOWNERS, .github/workflows/pr-assigner.yml
> 변경 사항 설명
- PR code reviewer 자동 할당 설정 추가
- PR assignees 자동 할당 설정 추가
- x
- Team 설정을 통해 code reviewer 할당을 할 수 있다는 것
- x
- x
- close #27
=> [Feature/27] pr assignees와 reviewer 할당 자동화

src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java, src/main/java/com/example/namo2/domain/moim/application/converter/MoimResponseConverter.java, src/main/java/com/example/namo2/domain/moim/ui/MoimController.java, src/main/java/com/example/namo2/domain/moim/ui/dto/MoimResponse.java
> 변경 사항 설명
- MoimFacade.java
- createMoimAndUser 에서 반환하는 값을 바꿔준다.
- MoimResponse.java
- MoimParticipantDto 를 통해 code와 moimId를 반환한다.
-
- 
- 
-
- close #44
=> [Feature/44]모임 참가 API Response 수정

src/main/java/com/example/namo2/domain/category/application/CategoryFacade.java, src/main/java/com/example/namo2/domain/category/application/impl/CategoryService.java, src/main/java/com/example/namo2/domain/category/ui/CategoryController.java, src/main/java/com/example/namo2/domain/category/ui/dto/CategoryRequest.java, src/main/java/com/example/namo2/domain/category/validation/annotation/CategoryName.java, src/main/java/com/example/namo2/domain/category/validation/validator/CategoryValidator.java, src/main/java/com/example/namo2/domain/user/application/UserFacade.java, src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
> 변경 사항 설명
- CategoryFacade.java
- Facade 계층에 Transaction 추가
- CategoryRequest.java, CategoryController.java
- 애노테이션을 통한 검증 로직 추가
- CategoryName.java
- 검증을 위한 애노테이션 추가
- CategoryValidator.java
- 검증을 위한 로직 추가
- BaseResponseStatus.java
- 새로운 오류 처리를 위한 코드 추가
- CategoryService.java
- validateBaseCategory 를 이용해서 기존의 카테고리 중 기본 카테고리에 대해서는 수정 불가능하게 validation 처리
- UserFacade.java
- makeBaseCategory 에서 기본 생성 카테고리 이름 바꾸기
- 기본 -> 일정
-
- CustomAnnotation 을 통한 검증 처리
- CustomAnnotation 에 대한 예외 처리
- 예외 코드와 예외 처리에 대한 부분을 한 번은 제대로 손을 봐야 할 듯 합니다.
- 모든 예외를 BaseException 으로 커스텀해서 처리할지에 대해서 고민중입니다.  
- https://hogwart-scholars.tistory.com/entry/Spring-Boot-ConstraintValidator%EB%A5%BC-%EC%9D% …
=> [Feature/46] 기본 카테고리 삭제 오류 수정

src/main/java/com/example/namo2/domain/memo/application/MoimMemoFacade.java, src/main/java/com/example/namo2/domain/memo/application/impl/MoimMemoLocationService.java, src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoLocationRepository.java, src/main/java/com/example/namo2/domain/memo/ui/MoimMemoController.java, src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java, src/main/java/com/example/namo2/domain/moim/application/MoimScheduleFacade.java, src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleAndUserService.java, src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleService.java, src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleRepository.java, src/main/java/com/example/namo2/domain/moim/domain/MoimSchedule.java, src/main/java/com/example/namo2/domain/moim/domain/MoimScheduleStatus.java, src/main/java/com/example/namo2/domain/schedule/application/ScheduleFacade.java
> 변경 사항 설명
- ScheduleFacade.java
- moimScheduleAlarm 도 같이 제거되어야함.
- ScheduleFacade.java
- Schedule에서 모임 스케줄 삭제 시 마지막 사람인 경우 모임 스케줄이 삭제되어야함
- MoimSchedule.java, MoimScheduleStatus.java
- MoimSchedule 을 soft delete 만 하기
- MoimMemoController.java
- removeMoimMemoLocation 으로 메서드 네이밍 규칙에 맞게 재명명
- MoimMemoLocationService.java
- getMoimMemoLocationWithImgs 으로 method 의도에 맞게 재명명
-
- 
- 
-
- close #
=> [Feature/42] 모임 스케줄 및 모임 메모 삭제 로직 리팩토링

src/main/java/com/example/namo2/domain/schedule/application/ScheduleFacade.java, src/main/java/com/example/namo2/domain/schedule/application/impl/ImageService.java, src/main/java/com/example/namo2/domain/schedule/dao/repository/ImageRepository.java, src/main/java/com/example/namo2/domain/user/application/UserFacade.java
> 변경 사항 설명
- UserFacade - s3이미지 삭제
- ScheduleFacade - s3이미지 삭제
-
- 
- 
-
- close #64
=> [Feature/64]: 이미지 삭제 시 s3에 이미지도 삭제

src/main/java/com/example/namo2/domain/category/dao/repository/CategoryRepository.java, src/main/java/com/example/namo2/domain/moim/dao/repository/MoimAndUserRepository.java, src/main/java/com/example/namo2/domain/user/application/UserFacade.java, src/main/java/com/example/namo2/domain/user/application/converter/UserResponseConverter.java, src/main/java/com/example/namo2/domain/user/ui/AuthController.java, src/main/java/com/example/namo2/domain/user/ui/dto/UserResponse.java, src/main/java/com/example/namo2/global/utils/JwtUtils.java
> 변경 사항 설명
- 로그인시 새로운 유저인지 판별하는 필드 추가
- boolean newUser
- 네이버/카카오/애플로그인에 모두 적용  
-
- 
- 
-
- close #62
=> [Feature/62] 로그인시 새로운 유저인지 판별하는 필드 추가

Dockerfile, src/main/java/com/example/namo2/domain/test/ui/TestController.java, src/main/java/com/example/namo2/domain/test/ui/dto/TestResponse.java, src/main/java/com/example/namo2/global/logging/filter/ApiLoggingFilter.java, src/main/resources/application-dev.yml
<footer>
- 관련: #68
> 변경 사항 설명
- spring boot JarLauncher 관련 버전 문제 해결
- x
- x
- x
- x
- close #68
=> :bug: Fix: JarLauncher 에러 픽스

src/main/java/com/example/namo2/domain/category/dao/repository/CategoryRepository.java, src/main/java/com/example/namo2/domain/memo/application/MoimMemoFacade.java, src/main/java/com/example/namo2/domain/memo/application/impl/MoimMemoService.java, src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoRepository.java, src/main/java/com/example/namo2/domain/memo/ui/MoimMemoController.java, src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java, src/main/java/com/example/namo2/domain/moim/application/converter/MoimResponseConverter.java, src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleAndUserService.java, src/main/java/com/example/namo2/domain/moim/dao/repository/MoimAndUserRepository.java, src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleAndUserRepositoryImpl.java, src/main/java/com/example/namo2/domain/moim/domain/MoimScheduleAndUser.java, src/main/java/com/example/namo2/domain/moim/domain/VisibleStatus.java, src/main/java/com/example/namo2/domain/schedule/application/ScheduleFacade.java, src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
> 변경 사항 설명
- MoimResponseConverter.java, MoimFacade.java
- 모임 순서를 참석 순으로 반환하게끔 변경
- BaseResponseStatus.java
- 모임 메모 존재하지 않는 경우 오류 코드 추가
- MoimMemoController.java, MoimMemoFacade.java
- 모임 메모 장소 삭제 API 추가
- MoimMemoRepository.java, MoimMemoService.java
- 모임 메모와 장소들을 한 번에 끌고 오는 로직 추가
- MoimScheduleAndUser.java, VisibleStatus.java
- 보이는 수준에 따라 분리
- MoimScheduleAndUserService.java
- 개인 스케줄에서 모임 스케줄이 안보이게 하는 status로 변경
- MoimScheduleAndUser.java, ScheduleFacade.java
- PersonalSpace에서 지우는 로직 추가
- MoimScheduleAndUserRepositoryImpl.java
- VisibleStatus.ALL 인것만 보이게끔 변경
- VisibleStatus.java
- enum 클래스가 하나 추가 되었습니다.
- 주석을 통해서 어떤 역할을 하는지는 간단하게 달아두었습니다.
- 개인 메모 혹은 스케줄에서 삭제할 때 상태를 변화시켜 보이는 레벨을 바꾸기 위해서 도입하였습니다.
- 데이터 베이스에 …
=> [Feature/61] 그룹 관련 요구 사항 및 디버깅 작업

src/main/java/com/example/namo2/domain/category/application/impl/CategoryService.java, src/main/java/com/example/namo2/domain/memo/application/MoimMemoFacade.java, src/main/java/com/example/namo2/domain/moim/application/MoimScheduleFacade.java, src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleAndUserService.java, src/main/java/com/example/namo2/domain/moim/application/impl/MoimService.java, src/main/java/com/example/namo2/domain/moim/dao/repository/MoimRepository.java, src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleRepository.java, src/main/java/com/example/namo2/domain/moim/ui/MoimScheduleController.java, src/main/java/com/example/namo2/domain/user/application/impl/UserService.java, src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java, src/main/java/com/example/namo2/global/utils/Converter.java
> 변경 사항 설명
- CategoryService.java
- 카테고리에 기본 카테고리가 없을 경우 검증 추가
- MoimRepository.java
- 모임과 모임참여자를 한번에 끌고 오는 로직 추가
- MoimScheduleAndUserService.java, MoimScheduleFacade.java
- 모임 스케줄 안에 유저가 모임 내의 유저인지 검증
- MoimService.java, UserService.java
- 이름 재명명
- MoimScheduleController.java, MoimScheduleFacade.java
- userId 와 moimScheduleId 를 통해서 모임 유저가 아닐 시 모임 스케줄 삭제 불가능하게함
- MoimScheduleRepository.java
- join -> left join 으로 변경
- MoimScheduleController.java, Converter.java
- 형식적 검증 로직 추가
- MoimScheduleFacade.java
- 모임에 속하지 않으면 모임 스케줄 볼 수 없게 변경
-
- 
- 
-
- close #55
=> [Feat] 모임 스케줄 Validation 검증 로직 및 비기능 개발

src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java, src/main/java/com/example/namo2/domain/moim/application/converter/MoimResponseConverter.java
> 변경 사항 설명
- MoimFacade.java, MoimResponseConverter.java
- MoimAndUser 에서 개인의 커스텀된 이름을 가져오게끔 변경
-
- 
- 
-
- close #74
=> [Feature/74] 모임 조회시 개인 커스텀 이름으로 조회하게끔 변경

src/main/java/com/example/namo2/global/config/interceptor/InterceptorConfig.java, src/main/java/com/example/namo2/global/logging/filter/ApiLoggingFilter.java
> 변경 사항 설명
- ApiLoggingFilter 수정
- TEXT 미디어 타입에 대한 로그 필터 제거
-
- 
- 
-
- close #82
=> [Fature/82] 스웨거 동작 오류 해결

src/main/java/com/example/namo2/global/logging/filter/ApiLoggingFilter.java, src/main/resources/application-docs.yml
> 변경 사항 설명
- 스웨거 패키지 스캔 설정 수정
- close #82
=> [Feature/82] 스웨거 패키지 스캔 관련 설정 수정

src/main/java/com/example/namo2/global/config/logging/ApiLoggingFilter.java, src/main/java/com/example/namo2/global/config/web/CorsFilter.java
> 변경 사항 설명
- Cors 문제 해결을 위한 filter 추가
- close #88
=> [Feature/88] Cors 문제 해결

src/main/java/com/example/namo2/domain/category/ui/CategoryController.java, src/main/java/com/example/namo2/domain/memo/ui/MoimMemoController.java, src/main/java/com/example/namo2/domain/moim/ui/MoimController.java, src/main/java/com/example/namo2/domain/moim/ui/MoimScheduleController.java, src/main/java/com/example/namo2/domain/schedule/ui/ScheduleController.java, src/main/java/com/example/namo2/domain/test/ui/TestController.java, src/main/java/com/example/namo2/domain/user/ui/AuthController.java, src/main/java/com/example/namo2/global/annotation/swagger/ApiErrorCode.java, src/main/java/com/example/namo2/global/annotation/swagger/ApiErrorCodes.java, src/main/java/com/example/namo2/global/config/properties/ExampleHolder.java, src/main/java/com/example/namo2/global/config/swagger/SwaggerConfig.java, src/main/resources/application-docs.yml
> 변경 사항 설명
- SwaggerConfig 수정
- Operation Customizer 구현
- 커스텀 Annotation을 트리거로 사용하여 api에 커스텀 Annotation이 존재한다면 로직을 통해 Operation이 Custom 됨
- HTTPS 요청으로 api test를 할 수 있게 함으로 CORS 문제 해결
- token header 등록 가능하도록 수정
- 커스텀 Annotation
- ApiErrorCodes : 복수의 에러를 다루는 커스텀 어노테이션
- ApiErrorCode : 단일 에러를 다루는 커스텀 어노테이션
- 전체 Controller
-  Jwt와 500번 관련 에러에 대한 공통 에러 응답 등록
-
- OperationCustomizer를 통해 view를 커스텀하는 방법
- 커스텀 어노테이션을 통해 코드 중복을 어디까지 줄일 수 있을지 고민
- https://leeeeeyeon-dev.tistory.com/92
- close #90
=> [Feature/90] Swagger api test 환경 구축

src/main/java/com/example/namo2/domain/category/ui/CategoryController.java, src/main/java/com/example/namo2/domain/memo/ui/GroupDiaryController.java, src/main/java/com/example/namo2/domain/moim/ui/GroupController.java, src/main/java/com/example/namo2/domain/moim/ui/GroupScheduleController.java, src/main/java/com/example/namo2/domain/schedule/ui/DiaryController.java, src/main/java/com/example/namo2/domain/schedule/ui/ScheduleController.java, src/main/java/com/example/namo2/domain/test/ui/TestController.java, src/main/java/com/example/namo2/domain/user/ui/AuthController.java, src/main/java/com/example/namo2/domain/user/ui/TermController.java, src/main/java/com/example/namo2/global/config/swagger/SwaggerConfig.java, src/main/resources/application-docs.yml
> 변경 사항 설명
- api url 수정
- api 버저닝 준비
- api/v1 path 추가
- swagger 그룹 설정
- close #92
=> [Feature/92] API 버저닝 준비 및 url 수정

build.gradle, src/main/java/com/example/namo2/domain/group/application/MoimFacade.java, src/main/java/com/example/namo2/domain/group/application/MoimMemoFacade.java, src/main/java/com/example/namo2/domain/individual/application/DiaryFacade.java, src/main/java/com/example/namo2/global/common/constant/FilePath.java, src/main/java/com/example/namo2/global/config/interceptor/InterceptorConfig.java, src/main/java/com/example/namo2/global/utils/FileUtils.java, src/main/java/com/example/namo2/global/utils/S3Uploader.java
> 변경 사항 설명
- S3 FilePath 관리용 enum 클래스 작성
- javax 관련 xml bind 의존성 추가
- S3 파일 업로드 로직 수정
-
- 
- 
-
- close #101
=> [Feature/101] 이미지 저장 로직 수정

src/main/java/com/example/namo2/domain/group/ui/GroupController.java, src/main/java/com/example/namo2/domain/group/ui/GroupDiaryController.java, src/main/java/com/example/namo2/domain/individual/ui/DiaryController.java, src/main/java/com/example/namo2/global/utils/JwtUtils.java
> 변경 사항 설명
- Jwt 인증 과정에 Bearer 추가
- Swagger 내에서 Multipart/form-data test 진행할 수 있도록 구성
-
- 
- 
-
- close #103
=> [Feature/103] 스웨거 test 환경 구축

src/main/java/com/example/namo2/domain/group/ui/GroupController.java, src/main/java/com/example/namo2/domain/group/ui/GroupDiaryController.java, src/main/java/com/example/namo2/domain/group/ui/GroupScheduleController.java, src/main/java/com/example/namo2/domain/individual/ui/CategoryController.java, src/main/java/com/example/namo2/domain/individual/ui/DiaryController.java, src/main/java/com/example/namo2/domain/individual/ui/ScheduleController.java, src/main/java/com/example/namo2/domain/user/ui/AuthController.java, src/main/java/com/example/namo2/domain/user/ui/TermController.java
> 변경 사항 설명
- 스웨거 api 설명 수정
- 파라미터 설명이 언어 정의에 맞는지 확인 부탁드립니다.
- 
- 
-
- close #105
=> [Feature/105] 스웨거 설명 수정

src/main/java/com/example/namo2/global/config/logging/ApiLoggingFilter.java
> 변경 사항 설명
- multipart request 에 대한 로깅 기능을 추가했습니다.
- close #107
=> [feature/107] Multipart/from-data logging 기능 추가

src/main/java/com/example/namo2/domain/group/application/MoimMemoFacade.java, src/main/java/com/example/namo2/domain/group/application/impl/MoimMemoLocationService.java, src/main/java/com/example/namo2/domain/group/domain/MoimMemo.java, src/main/java/com/example/namo2/domain/individual/application/converter/ScheduleResponseConverter.java, src/main/java/com/example/namo2/domain/individual/ui/dto/ScheduleResponse.java, src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
> 변경 사항 설명
- hasDiary 관련한 요구사항에 맞춰서 추가
- 모임 메모 장소가 3개 이상으로 넘어가는 로직에 대한 검증 로직 추가
- ScheduleResponseConverter.java
- 각각의 상태에 대한 올바른 상태 값 추가
- ScheduleResponse.java
- Boolean 으로 타입 변경
- BaesResponseStatus.java
- 에러 코드 추가
- MoimMemo.java
- 장소가 3개 이상인지 확인하는 로직 추가
- MoimMemoLocationService.java
- 장소가 3개 이상일 경우 Exception 을 추가
-
- 
- 
-
- close #109
=> [feature/109] hasDiary 기능 추가, 모임 메모장소 3개 제한 로직 추가

src/main/java/com/example/namo2/domain/user/application/UserFacade.java, src/main/java/com/example/namo2/global/feignclient/kakao/KakaoAuthClient.java, src/main/java/com/example/namo2/global/utils/JwtUtils.java
> 변경 사항 설명
- 회원 탈퇴 로직 500번대 에러 발생에 따른 token validation 로직 수정 진행
- close #110
=> [Feature/110] 회원 탈퇴 Jwt 토큰 로직 수정

src/main/java/com/example/namo2/domain/group/application/MoimMemoFacade.java, src/main/java/com/example/namo2/domain/group/application/MoimScheduleFacade.java, src/main/java/com/example/namo2/domain/group/application/impl/MoimMemoService.java, src/main/java/com/example/namo2/domain/group/dao/repository/diary/MoimMemoRepository.java, src/main/java/com/example/namo2/domain/group/ui/GroupDiaryController.java, src/main/java/com/example/namo2/domain/individual/application/DiaryFacade.java, src/main/java/com/example/namo2/domain/individual/application/ScheduleFacade.java, src/main/java/com/example/namo2/domain/user/application/UserFacade.java, src/main/java/com/example/namo2/global/config/logging/ApiLoggingFilter.java, src/main/java/com/example/namo2/global/utils/FileUtils.java
> 변경 사항 설명
- 모임 기록 삭제 api 파라미터 수정
- File 삭제 로직 수정
- contentType check 로직 수정
-
- close #112
=> [Feature/112] 모임 기록 삭제(그룹) api 파라미터 변경

src/main/java/com/example/namo2/domain/individual/ui/DiaryController.java
> 변경 사항 설명
- 일정 기록 월간 조회 api uri 수정
- close #115
=> [feature/115] 월간 기록 조회 이슈 해결

src/main/java/com/example/namo2/domain/individual/dao/repository/schedule/ScheduleRepositoryImpl.java
> 변경 사항 설명
- 반환 값에 대한 임시 필터 추가
- close #120
=> [feature/120] 개인이 삭제한 모임 일정이 타 모임 캘린더에서 보이는 오류 수정
